<?php

use Illuminate\Database\Seeder;
use Modules\Admin\Entities\AdminMenu;

class AdminMenuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        AdminMenu::truncate();
        $data = [
            [
                'id' => '1',
                'action_id' => '0',
                'view' => '',
                'link' => '',
                'icon' => 'fas fa-tachometer-alt',
                'icon_thumb' => '',
                'display_order' => '1',
                'name' => 'Dashboard',
                'type' => AdminMenu::TYPE_BACK_END,
                'parent_id' => '0',
            ],
            [
                'id' => '2',
                'action_id' => '1',
                'view' => '',
                'link' => '',
                'icon' => '',
                'icon_thumb' => '',
                'display_order' => '1',
                'name' => 'Modules',
                'type' => AdminMenu::TYPE_BACK_END,
                'parent_id' => '10',
            ],
            [
                'id' => '3',
                'action_id' => '5',
                'view' => '',
                'link' => '',
                'icon' => '',
                'icon_thumb' => '',
                'display_order' => '2',
                'name' => 'Controllers',
                'type' => AdminMenu::TYPE_BACK_END,
                'parent_id' => '10',
            ],
            [
                'id' => '4',
                'action_id' => '9',
                'view' => '',
                'link' => '',
                'icon' => '',
                'icon_thumb' => '',
                'display_order' => '3',
                'name' => 'Actions',
                'type' => AdminMenu::TYPE_BACK_END,
                'parent_id' => '10',
            ],
            [
                'id' => '5',
                'action_id' => '13',
                'view' => '',
                'link' => '',
                'icon' => '',
                'icon_thumb' => '',
                'display_order' => '4',
                'name' => 'Menu',
                'type' => AdminMenu::TYPE_BACK_END,
                'parent_id' => '1',
            ],
            [
                'id' => '6',
                'action_id' => '17',
                'view' => '',
                'link' => '',
                'icon' => '',
                'icon_thumb' => '',
                'display_order' => '5',
                'name' => 'Role',
                'type' => AdminMenu::TYPE_BACK_END,
                'parent_id' => '1',
            ],
            [
                'id' => '7',
                'action_id' => '22',
                'view' => '',
                'link' => '',
                'icon' => '',
                'icon_thumb' => '',
                'display_order' => '6',
                'name' => 'Loggers',
                'type' => AdminMenu::TYPE_BACK_END,
                'parent_id' => '10',
            ],
            [
                'id' => '8',
                'action_id' => '25',
                'view' => '',
                'link' => '',
                'icon' => '',
                'icon_thumb' => '',
                'display_order' => '7',
                'name' => 'Record Logs',
                'type' => AdminMenu::TYPE_BACK_END,
                'parent_id' => '10',
            ],
            [
                'id' => '9',
                'action_id' => '26',
                'view' => '',
                'link' => '',
                'icon' => '',
                'icon_thumb' => '',
                'display_order' => '8',
                'name' => 'Activity Logs',
                'type' => AdminMenu::TYPE_BACK_END,
                'parent_id' => '10',
            ],
            [
                'id' => '10',
                'action_id' => '0',
                'view' => '',
                'link' => '',
                'icon' => 'far fa-check-square',
                'icon_thumb' => '',
                'display_order' => '2',
                'name' => 'Development',
                'type' => AdminMenu::TYPE_BACK_END,
                'parent_id' => '0',
            ],
            [
                'id' => '11',
                'action_id' => '27',
                'view' => '',
                'link' => '',
                'icon' => '',
                'icon_thumb' => '',
                'display_order' => '3',
                'name' => 'Users',
                'type' => AdminMenu::TYPE_BACK_END,
                'parent_id' => '1',
            ],
            [
                'id' => '12',
                'action_id' => '32',
                'view' => '',
                'link' => '',
                'icon' => '',
                'icon_thumb' => '',
                'display_order' => '9',
                'name' => 'Page count',
                'type' => AdminMenu::TYPE_BACK_END,
                'parent_id' => '10',
            ],
            [
                'id' => '13',
                'action_id' => '33',
                'view' => '',
                'link' => '',
                'icon' => '',
                'icon_thumb' => '',
                'display_order' => '10',
                'name' => 'Automation Emails',
                'type' => AdminMenu::TYPE_BACK_END,
                'parent_id' => '10',
            ],
            [
                'id' => '14',
                'action_id' => '36',
                'view' => '',
                'link' => '',
                'icon' => '',
                'icon_thumb' => '',
                'display_order' => '11',
                'name' => 'Address',
                'type' => AdminMenu::TYPE_BACK_END,
                'parent_id' => '10',
            ],
            [
                'id' => '15',
                'action_id' => '61',
                'view' => '',
                'link' => '',
                'icon' => '',
                'icon_thumb' => '',
                'display_order' => '5',
                'name' => 'Settings',
                'type' => AdminMenu::TYPE_BACK_END,
                'parent_id' => '10',
            ],
            [
                'id' => '16',
                'action_id' => '0',
                'view' => '',
                'link' => '',
                'icon' => 'far fa-check-square',
                'icon_thumb' => '',
                'display_order' => '3',
                'name' => 'Api',
                'type' => AdminMenu::TYPE_BACK_END,
                'parent_id' => '0',
            ],
            [
                'id' => '17',
                'action_id' => '66',
                'view' => '',
                'link' => '',
                'icon' => 'far fa-check-square',
                'icon_thumb' => '',
                'display_order' => '12',
                'name' => 'One Many',
                'type' => AdminMenu::TYPE_BACK_END,
                'parent_id' => '10',
            ],
            [
                'id' => '19',
                'action_id' => '0',
                'view' => '',
                'link' => '',
                'icon' => 'fas fa-tachometer-alt',
                'icon_thumb' => '',
                'display_order' => '3',
                'name' => 'New Features ',
                'type' => AdminMenu::TYPE_BACK_END,
                'parent_id' => '0',
            ],
            [
                'id' => '20',
                'action_id' => '76',
                'view' => '',
                'link' => '',
                'icon' => 'far fa-check-square',
                'icon_thumb' => '',
                'display_order' => '1',
                'name' => 'Calendar',
                'type' => AdminMenu::TYPE_BACK_END,
                'parent_id' => '19',
            ],
            [
                'id' => '21',
                'action_id' => '71',
                'view' => '',
                'link' => '',
                'icon' => 'far fa-check-square',
                'icon_thumb' => '',
                'display_order' => '13',
                'name' => 'Files',
                'type' => AdminMenu::TYPE_BACK_END,
                'parent_id' => '10',
            ],
            [
                'id' => '22',
                'action_id' => '81',
                'view' => '',
                'link' => '',
                'icon' => 'far fa-check-square',
                'icon_thumb' => '',
                'display_order' => '14',
                'name' => 'Notification',
                'type' => AdminMenu::TYPE_BACK_END,
                'parent_id' => '10',
            ],
        ];
        AdminMenu::insert($data);
    }
}
