<?php

use Illuminate\Database\Seeder;
use Modules\Admin\Entities\AdminAddressCity;

class AdminAddressCitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        AdminAddressCity::truncate();
        $data = [
//            ['id' => '1','nation_id' => '239','name' => 'Hà Nội','short_name' => 'ha noi','slug' => 'ha-noi','code_no' => '01',],
//            ['id' => '2','nation_id' => '239','name' => 'TP Hồ Chí Minh','short_name' => 'tp ho chi minh','slug' => 'tp-ho-chi-minh','code_no' => '79',],
//            ['id' => '3','nation_id' => '239','name' => 'Hải Phòng','short_name' => 'hai phong','slug' => 'hai-phong','code_no' => '31',],
//            ['id' => '4','nation_id' => '239','name' => 'Đà Nẵng','short_name' => 'da nang','slug' => 'da-nang','code_no' => '48',],
//            ['id' => '5','nation_id' => '239','name' => 'Hà Giang','short_name' => 'ha giang','slug' => 'ha-giang','code_no' => '02',],
//            ['id' => '6','nation_id' => '239','name' => 'Cao Bằng','short_name' => 'cao bang','slug' => 'cao-bang','code_no' => '04',],
//            ['id' => '7','nation_id' => '239','name' => 'Lai Châu','short_name' => 'lai chau','slug' => 'lai-chau','code_no' => '12',],
//            ['id' => '8','nation_id' => '239','name' => 'Lào Cai','short_name' => 'lao cai','slug' => 'lao-cai','code_no' => '10',],
//            ['id' => '9','nation_id' => '239','name' => 'Tuyên Quang','short_name' => 'tuyen quang','slug' => 'tuyen-quang','code_no' => '08',],
//            ['id' => '10','nation_id' => '239','name' => 'Lạng Sơn','short_name' => 'lang son','slug' => 'lang-son','code_no' => '20',],
//            ['id' => '11','nation_id' => '239','name' => 'Bắc Kạn','short_name' => 'bac kan','slug' => 'bac-kan','code_no' => '06',],
//            ['id' => '12','nation_id' => '239','name' => 'Thái Nguyên','short_name' => 'thai nguyen','slug' => 'thai-nguyen','code_no' => '19',],
//            ['id' => '13','nation_id' => '239','name' => 'Yên Bái','short_name' => 'yen bai','slug' => 'yen-bai','code_no' => '15',],
//            ['id' => '14','nation_id' => '239','name' => 'Sơn La','short_name' => 'son la','slug' => 'son-la','code_no' => '14',],
//            ['id' => '15','nation_id' => '239','name' => 'Phú Thọ','short_name' => 'phu tho','slug' => 'phu-tho','code_no' => '25',],
//            ['id' => '16','nation_id' => '239','name' => 'Vĩnh Phúc','short_name' => 'vinh phuc','slug' => 'vinh-phuc','code_no' => '26',],
//            ['id' => '17','nation_id' => '239','name' => 'Quảng Ninh','short_name' => 'quang ninh','slug' => 'quang-ninh','code_no' => '22',],
//            ['id' => '18','nation_id' => '239','name' => 'Bắc Giang','short_name' => 'bac giang','slug' => 'bac-giang','code_no' => '24',],
//            ['id' => '19','nation_id' => '239','name' => 'Bắc Ninh','short_name' => 'bac ninh','slug' => 'bac-ninh','code_no' => '27',],
//            ['id' => '20','nation_id' => '239','name' => 'Hà Tây','short_name' => 'ha tay','slug' => 'ha-tay','code_no' => '0',],
//            ['id' => '21','nation_id' => '239','name' => 'Hải Dương','short_name' => 'hai duong','slug' => 'hai-duong','code_no' => '30',],
//            ['id' => '22','nation_id' => '239','name' => 'Hưng Yên','short_name' => 'hung yen','slug' => 'hung-yen','code_no' => '33',],
//            ['id' => '23','nation_id' => '239','name' => 'Hòa Bình','short_name' => 'hoa binh','slug' => 'hoa-binh','code_no' => '17',],
//            ['id' => '24','nation_id' => '239','name' => 'Hà Nam','short_name' => 'ha nam','slug' => 'ha-nam','code_no' => '35',],
//            ['id' => '25','nation_id' => '239','name' => 'Nam Định','short_name' => 'nam dinh','slug' => 'nam-dinh','code_no' => '36',],
//            ['id' => '26','nation_id' => '239','name' => 'Thái Bình','short_name' => 'thai binh','slug' => 'thai-binh','code_no' => '34',],
//            ['id' => '27','nation_id' => '239','name' => 'Ninh Bình','short_name' => 'ninh binh','slug' => 'ninh-binh','code_no' => '37',],
//            ['id' => '28','nation_id' => '239','name' => 'Thanh Hóa','short_name' => 'thanh hoa','slug' => 'thanh-hoa','code_no' => '38',],
//            ['id' => '29','nation_id' => '239','name' => 'Nghệ An','short_name' => 'nghe an','slug' => 'nghe-an','code_no' => '40',],
//            ['id' => '30','nation_id' => '239','name' => 'Hà Tĩnh','short_name' => 'ha tinh','slug' => 'ha-tinh','code_no' => '42',],
//            ['id' => '31','nation_id' => '239','name' => 'Quảng Bình','short_name' => 'quang binh','slug' => 'quang-binh','code_no' => '44',],
//            ['id' => '32','nation_id' => '239','name' => 'Quảng Trị','short_name' => 'quang tri','slug' => 'quang-tri','code_no' => '45',],
//            ['id' => '33','nation_id' => '239','name' => 'Thừa Thiên Huế','short_name' => 'thua thien hue','slug' => 'thua-thien-hue','code_no' => '46',],
//            ['id' => '34','nation_id' => '239','name' => 'Quảng Nam','short_name' => 'quang nam','slug' => 'quang-nam','code_no' => '49',],
//            ['id' => '35','nation_id' => '239','name' => 'Quảng Ngãi','short_name' => 'quang ngai','slug' => 'quang-ngai','code_no' => '51',],
//            ['id' => '36','nation_id' => '239','name' => 'Kon Tum','short_name' => 'kon tum','slug' => 'kon-tum','code_no' => '62',],
//            ['id' => '37','nation_id' => '239','name' => 'Bình Định','short_name' => 'binh dinh','slug' => 'binh-dinh','code_no' => '52',],
//            ['id' => '38','nation_id' => '239','name' => 'Gia Lai','short_name' => 'gia lai','slug' => 'gia-lai','code_no' => '64',],
//            ['id' => '39','nation_id' => '239','name' => 'Phú Yên','short_name' => 'phu yen','slug' => 'phu-yen','code_no' => '54',],
//            ['id' => '40','nation_id' => '239','name' => 'Đắk Lắk','short_name' => 'dak lak','slug' => 'dak-lak','code_no' => '66',],
//            ['id' => '41','nation_id' => '239','name' => 'Khánh Hòa','short_name' => 'khanh hoa','slug' => 'khanh-hoa','code_no' => '56',],
//            ['id' => '42','nation_id' => '239','name' => 'Lâm Đồng','short_name' => 'lam dong','slug' => 'lam-dong','code_no' => '68',],
//            ['id' => '43','nation_id' => '239','name' => 'Bình Phước','short_name' => 'binh phuoc','slug' => 'binh-phuoc','code_no' => '70',],
//            ['id' => '44','nation_id' => '239','name' => 'Bình Dương','short_name' => 'binh duong','slug' => 'binh-duong','code_no' => '74',],
//            ['id' => '45','nation_id' => '239','name' => 'Ninh Thuận','short_name' => 'ninh thuan','slug' => 'ninh-thuan','code_no' => '58',],
//            ['id' => '46','nation_id' => '239','name' => 'Tây Ninh','short_name' => 'tay ninh','slug' => 'tay-ninh','code_no' => '72',],
//            ['id' => '47','nation_id' => '239','name' => 'Bình Thuận','short_name' => 'binh thuan','slug' => 'binh-thuan','code_no' => '60',],
//            ['id' => '48','nation_id' => '239','name' => 'Đồng Nai','short_name' => 'dong nai','slug' => 'dong-nai','code_no' => '75',],
//            ['id' => '49','nation_id' => '239','name' => 'Long An','short_name' => 'long an','slug' => 'long-an','code_no' => '80',],
//            ['id' => '50','nation_id' => '239','name' => 'Đồng Tháp','short_name' => 'dong thap','slug' => 'dong-thap','code_no' => '87',],
//            ['id' => '51','nation_id' => '239','name' => 'An Giang','short_name' => 'an giang','slug' => 'an-giang','code_no' => '89',],
//            ['id' => '52','nation_id' => '239','name' => 'Bà Rịa - Vũng Tàu','short_name' => 'ba ria - vung tau','slug' => 'ba-ria---vung-tau','code_no' => '77',],
//            ['id' => '53','nation_id' => '239','name' => 'Tiền Giang','short_name' => 'tien giang','slug' => 'tien-giang','code_no' => '82',],
//            ['id' => '54','nation_id' => '239','name' => 'Kiên Giang','short_name' => 'kien giang','slug' => 'kien-giang','code_no' => '91',],
//            ['id' => '55','nation_id' => '239','name' => 'Cần Thơ','short_name' => 'can tho','slug' => 'can-tho','code_no' => '92',],
//            ['id' => '56','nation_id' => '239','name' => 'Bến Tre','short_name' => 'ben tre','slug' => 'ben-tre','code_no' => '83',],
//            ['id' => '57','nation_id' => '239','name' => 'Vĩnh Long','short_name' => 'vinh long','slug' => 'vinh-long','code_no' => '86',],
//            ['id' => '58','nation_id' => '239','name' => 'Trà Vinh','short_name' => 'tra vinh','slug' => 'tra-vinh','code_no' => '84',],
//            ['id' => '59','nation_id' => '239','name' => 'Sóc Trăng','short_name' => 'soc trang','slug' => 'soc-trang','code_no' => '94',],
//            ['id' => '60','nation_id' => '239','name' => 'Bạc Liêu','short_name' => 'bac lieu','slug' => 'bac-lieu','code_no' => '95',],
//            ['id' => '61','nation_id' => '239','name' => 'Cà Mau','short_name' => 'ca mau','slug' => 'ca-mau','code_no' => '96',],
//            ['id' => '62','nation_id' => '239','name' => 'Điện Biên','short_name' => 'dien bien','slug' => 'dien-bien','code_no' => '11',],
//            ['id' => '63','nation_id' => '239','name' => 'Đắk Nông','short_name' => 'dak nong','slug' => 'dak-nong','code_no' => '67',],
//            ['id' => '64','nation_id' => '239','name' => 'Hậu Giang','short_name' => 'hau giang','slug' => 'hau-giang','code_no' => '93',],
            ['id' => '65','nation_id' => '111','name' => '北海道','short_name' => '北海道','slug' => '北海道','code_no' => '1',],
            ['id' => '66','nation_id' => '111','name' => '青森県','short_name' => '青森県','slug' => '青森県','code_no' => '2',],
            ['id' => '67','nation_id' => '111','name' => '岩手県','short_name' => '岩手県','slug' => '岩手県','code_no' => '3',],
            ['id' => '68','nation_id' => '111','name' => '宮城県','short_name' => '宮城県','slug' => '宮城県','code_no' => '4',],
            ['id' => '69','nation_id' => '111','name' => '秋田県','short_name' => '秋田県','slug' => '秋田県','code_no' => '5',],
            ['id' => '70','nation_id' => '111','name' => '山形県','short_name' => '山形県','slug' => '山形県','code_no' => '6',],
            ['id' => '71','nation_id' => '111','name' => '福島県','short_name' => '福島県','slug' => '福島県','code_no' => '7',],
            ['id' => '72','nation_id' => '111','name' => '茨城県','short_name' => '茨城県','slug' => '茨城県','code_no' => '8',],
            ['id' => '73','nation_id' => '111','name' => '栃木県','short_name' => '栃木県','slug' => '栃木県','code_no' => '9',],
            ['id' => '74','nation_id' => '111','name' => '群馬県','short_name' => '群馬県','slug' => '群馬県','code_no' => '10',],
            ['id' => '75','nation_id' => '111','name' => '埼玉県','short_name' => '埼玉県','slug' => '埼玉県','code_no' => '11',],
            ['id' => '76','nation_id' => '111','name' => '千葉県','short_name' => '千葉県','slug' => '千葉県','code_no' => '12',],
            ['id' => '77','nation_id' => '111','name' => '東京都','short_name' => '東京都','slug' => '東京都','code_no' => '13',],
            ['id' => '78','nation_id' => '111','name' => '神奈川県','short_name' => '神奈川県','slug' => '神奈川県','code_no' => '14',],
            ['id' => '79','nation_id' => '111','name' => '新潟県','short_name' => '新潟県','slug' => '新潟県','code_no' => '15',],
            ['id' => '80','nation_id' => '111','name' => '富山県','short_name' => '富山県','slug' => '富山県','code_no' => '16',],
            ['id' => '81','nation_id' => '111','name' => '石川県','short_name' => '石川県','slug' => '石川県','code_no' => '17',],
            ['id' => '82','nation_id' => '111','name' => '福井県','short_name' => '福井県','slug' => '福井県','code_no' => '18',],
            ['id' => '83','nation_id' => '111','name' => '山梨県','short_name' => '山梨県','slug' => '山梨県','code_no' => '19',],
            ['id' => '84','nation_id' => '111','name' => '長野県','short_name' => '長野県','slug' => '長野県','code_no' => '20',],
            ['id' => '85','nation_id' => '111','name' => '岐阜県','short_name' => '岐阜県','slug' => '岐阜県','code_no' => '21',],
            ['id' => '86','nation_id' => '111','name' => '静岡県','short_name' => '静岡県','slug' => '静岡県','code_no' => '22',],
            ['id' => '87','nation_id' => '111','name' => '愛知県','short_name' => '愛知県','slug' => '愛知県','code_no' => '23',],
            ['id' => '88','nation_id' => '111','name' => '三重県','short_name' => '三重県','slug' => '三重県','code_no' => '24',],
            ['id' => '89','nation_id' => '111','name' => '滋賀県','short_name' => '滋賀県','slug' => '滋賀県','code_no' => '25',],
            ['id' => '90','nation_id' => '111','name' => '京都府','short_name' => '京都府','slug' => '京都府','code_no' => '26',],
            ['id' => '91','nation_id' => '111','name' => '大阪府','short_name' => '大阪府','slug' => '大阪府','code_no' => '27',],
            ['id' => '92','nation_id' => '111','name' => '兵庫県','short_name' => '兵庫県','slug' => '兵庫県','code_no' => '28',],
            ['id' => '93','nation_id' => '111','name' => '奈良県','short_name' => '奈良県','slug' => '奈良県','code_no' => '29',],
            ['id' => '94','nation_id' => '111','name' => '和歌山県','short_name' => '和歌山県','slug' => '和歌山県','code_no' => '30',],
            ['id' => '95','nation_id' => '111','name' => '鳥取県','short_name' => '鳥取県','slug' => '鳥取県','code_no' => '31',],
            ['id' => '96','nation_id' => '111','name' => '島根県','short_name' => '島根県','slug' => '島根県','code_no' => '32',],
            ['id' => '97','nation_id' => '111','name' => '岡山県','short_name' => '岡山県','slug' => '岡山県','code_no' => '33',],
            ['id' => '98','nation_id' => '111','name' => '広島県','short_name' => '広島県','slug' => '広島県','code_no' => '34',],
            ['id' => '99','nation_id' => '111','name' => '山口県','short_name' => '山口県','slug' => '山口県','code_no' => '35',],
            ['id' => '100','nation_id' => '111','name' => '徳島県','short_name' => '徳島県','slug' => '徳島県','code_no' => '36',],
            ['id' => '101','nation_id' => '111','name' => '香川県','short_name' => '香川県','slug' => '香川県','code_no' => '37',],
            ['id' => '102','nation_id' => '111','name' => '愛媛県','short_name' => '愛媛県','slug' => '愛媛県','code_no' => '38',],
            ['id' => '103','nation_id' => '111','name' => '高知県','short_name' => '高知県','slug' => '高知県','code_no' => '39',],
            ['id' => '104','nation_id' => '111','name' => '福岡県','short_name' => '福岡県','slug' => '福岡県','code_no' => '40',],
            ['id' => '105','nation_id' => '111','name' => '佐賀県','short_name' => '佐賀県','slug' => '佐賀県','code_no' => '41',],
            ['id' => '106','nation_id' => '111','name' => '長崎県','short_name' => '長崎県','slug' => '長崎県','code_no' => '42',],
            ['id' => '107','nation_id' => '111','name' => '熊本県','short_name' => '熊本県','slug' => '熊本県','code_no' => '43',],
            ['id' => '108','nation_id' => '111','name' => '大分県','short_name' => '大分県','slug' => '大分県','code_no' => '44',],
            ['id' => '109','nation_id' => '111','name' => '宮崎県','short_name' => '宮崎県','slug' => '宮崎県','code_no' => '45',],
            ['id' => '110','nation_id' => '111','name' => '鹿児島県','short_name' => '鹿児島県','slug' => '鹿児島県','code_no' => '46',],
            ['id' => '111','nation_id' => '111','name' => '沖縄県','short_name' => '沖縄県','slug' => '沖縄県','code_no' => '47',],            
        ];
        AdminAddressCity::insert($data);
    }
}
