<?php

use Illuminate\Database\Seeder;
use Modules\Admin\Entities\AdminAddressNation;


class AdminAddressNationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        AdminAddressNation::truncate();
        $data = [
            [
                'id'                    => '1',
                'name'                  => 'Afghanistan',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'AF',
            ],
            [
                'id'                    => '2',
                'name'                  => 'Albania',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'AL',
            ],
            [
                'id'                    => '3',
                'name'                  => 'Algeria',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'DZ',
            ],
            [
                'id'                    => '4',
                'name'                  => 'American Samoa',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'DS',
            ],
            [
                'id'                    => '5',
                'name'                  => 'Andorra',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'AD',
            ],
            [
                'id'                    => '6',
                'name'                  => 'Angola',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'AO',
            ],
            [
                'id'                    => '7',
                'name'                  => 'Anguilla',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'AI',
            ],
            [
                'id'                    => '8',
                'name'                  => 'Antarctica',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'AQ',
            ],
            [
                'id'                    => '9',
                'name'                  => 'Antigua and Barbuda',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'AG',
            ],
            [
                'id'                    => '10',
                'name'                  => 'Argentina',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'AR',
            ],
            [
                'id'                    => '11',
                'name'                  => 'Armenia',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'AM',
            ],
            [
                'id'                    => '12',
                'name'                  => 'Aruba',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'AW',
            ],
            [
                'id'                    => '13',
                'name'                  => 'Australia',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'AU',
            ],
            [
                'id'                    => '14',
                'name'                  => 'Austria',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'AT',
            ],
            [
                'id'                    => '15',
                'name'                  => 'Azerbaijan',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'AZ',
            ],
            [
                'id'                    => '16',
                'name'                  => 'Bahamas',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'BS',
            ],
            [
                'id'                    => '17',
                'name'                  => 'Bahrain',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'BH',
            ],
            [
                'id'                    => '18',
                'name'                  => 'Bangladesh',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'BD',
            ],
            [
                'id'                    => '19',
                'name'                  => 'Barbados',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'BB',
            ],
            [
                'id'                    => '20',
                'name'                  => 'Belarus',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'BY',
            ],
            [
                'id'                    => '21',
                'name'                  => 'Belgium',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'BE',
            ],
            [
                'id'                    => '22',
                'name'                  => 'Belize',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'BZ',
            ],
            [
                'id'                    => '23',
                'name'                  => 'Benin',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'BJ',
            ],
            [
                'id'                    => '24',
                'name'                  => 'Bermuda',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'BM',
            ],
            [
                'id'                    => '25',
                'name'                  => 'Bhutan',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'BT',
            ],
            [
                'id'                    => '26',
                'name'                  => 'Bolivia',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'BO',
            ],
            [
                'id'                    => '27',
                'name'                  => 'Bosnia and Herzegovina',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'BA',
            ],
            [
                'id'                    => '28',
                'name'                  => 'Botswana',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'BW',
            ],
            [
                'id'                    => '29',
                'name'                  => 'Bouvet Island',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'BV',
            ],
            [
                'id'                    => '30',
                'name'                  => 'Brazil',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'BR',
            ],
            [
                'id'                    => '31',
                'name'                  => 'British Indian Ocean Territory',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'IO',
            ],
            [
                'id'                    => '32',
                'name'                  => 'Brunei Darussalam',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'BN',
            ],
            [
                'id'                    => '33',
                'name'                  => 'Bulgaria',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'BG',
            ],
            [
                'id'                    => '34',
                'name'                  => 'Burkina Faso',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'BF',
            ],
            [
                'id'                    => '35',
                'name'                  => 'Burundi',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'BI',
            ],
            [
                'id'                    => '36',
                'name'                  => 'Cambodia',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'KH',
            ],
            [
                'id'                    => '37',
                'name'                  => 'Cameroon',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'CM',
            ],
            [
                'id'                    => '38',
                'name'                  => 'Canada',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'CA',
            ],
            [
                'id'                    => '39',
                'name'                  => 'Cape Verde',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'CV',
            ],
            [
                'id'                    => '40',
                'name'                  => 'Cayman Islands',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'KY',
            ],
            [
                'id'                    => '41',
                'name'                  => 'Central African Republic',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'CF',
            ],
            [
                'id'                    => '42',
                'name'                  => 'Chad',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'TD',
            ],
            [
                'id'                    => '43',
                'name'                  => 'Chile',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'CL',
            ],
            [
                'id'                    => '44',
                'name'                  => 'China',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'CN',
            ],
            [
                'id'                    => '45',
                'name'                  => 'Christmas Island',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'CX',
            ],
            [
                'id'                    => '46',
                'name'                  => 'Cocos (Keeling) Islands',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'CC',
            ],
            [
                'id'                    => '47',
                'name'                  => 'Colombia',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'CO',
            ],
            [
                'id'                    => '48',
                'name'                  => 'Comoros',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'KM',
            ],
            [
                'id'                    => '49',
                'name'                  => 'Democratic Republic of the Congo',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'CD',
            ],
            [
                'id'                    => '50',
                'name'                  => 'Republic of the Congo',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'CG',
            ],
            [
                'id'                    => '51',
                'name'                  => 'Cook Islands',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'CK',
            ],
            [
                'id'                    => '52',
                'name'                  => 'Costa Rica',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'CR',
            ],
            [
                'id'                    => '53',
                'name'                  => 'Croatia (Hrvatska)',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'HR',
            ],
            [
                'id'                    => '54',
                'name'                  => 'Cuba',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'CU',
            ],
            [
                'id'                    => '55',
                'name'                  => 'Cyprus',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'CY',
            ],
            [
                'id'                    => '56',
                'name'                  => 'Czech Republic',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'CZ',
            ],
            [
                'id'                    => '57',
                'name'                  => 'Denmark',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'DK',
            ],
            [
                'id'                    => '58',
                'name'                  => 'Djibouti',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'DJ',
            ],
            [
                'id'                    => '59',
                'name'                  => 'Dominica',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'DM',
            ],
            [
                'id'                    => '60',
                'name'                  => 'Dominican Republic',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'DO',
            ],
            [
                'id'                    => '61',
                'name'                  => 'East Timor',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'TP',
            ],
            [
                'id'                    => '62',
                'name'                  => 'Ecuador',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'EC',
            ],
            [
                'id'                    => '63',
                'name'                  => 'Egypt',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'EG',
            ],
            [
                'id'                    => '64',
                'name'                  => 'El Salvador',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'SV',
            ],
            [
                'id'                    => '65',
                'name'                  => 'Equatorial Guinea',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'GQ',
            ],
            [
                'id'                    => '66',
                'name'                  => 'Eritrea',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'ER',
            ],
            [
                'id'                    => '67',
                'name'                  => 'Estonia',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'EE',
            ],
            [
                'id'                    => '68',
                'name'                  => 'Ethiopia',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'ET',
            ],
            [
                'id'                    => '69',
                'name'                  => 'Falkland Islands (Malvinas)',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'FK',
            ],
            [
                'id'                    => '70',
                'name'                  => 'Faroe Islands',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'FO',
            ],
            [
                'id'                    => '71',
                'name'                  => 'Fiji',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'FJ',
            ],
            [
                'id'                    => '72',
                'name'                  => 'Finland',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'FI',
            ],
            [
                'id'                    => '73',
                'name'                  => 'France',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'FR',
            ],
            [
                'id'                    => '74',
                'name'                  => 'France, Metropolitan',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'FX',
            ],
            [
                'id'                    => '75',
                'name'                  => 'French Guiana',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'GF',
            ],
            [
                'id'                    => '76',
                'name'                  => 'French Polynesia',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'PF',
            ],
            [
                'id'                    => '77',
                'name'                  => 'French Southern Territories',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'TF',
            ],
            [
                'id'                    => '78',
                'name'                  => 'Gabon',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'GA',
            ],
            [
                'id'                    => '79',
                'name'                  => 'Gambia',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'GM',
            ],
            [
                'id'                    => '80',
                'name'                  => 'Georgia',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'GE',
            ],
            [
                'id'                    => '81',
                'name'                  => 'Germany',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'DE',
            ],
            [
                'id'                    => '82',
                'name'                  => 'Ghana',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'GH',
            ],
            [
                'id'                    => '83',
                'name'                  => 'Gibraltar',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'GI',
            ],
            [
                'id'                    => '84',
                'name'                  => 'Guernsey',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'GK',
            ],
            [
                'id'                    => '85',
                'name'                  => 'Greece',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'GR',
            ],
            [
                'id'                    => '86',
                'name'                  => 'Greenland',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'GL',
            ],
            [
                'id'                    => '87',
                'name'                  => 'Grenada',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'GD',
            ],
            [
                'id'                    => '88',
                'name'                  => 'Guadeloupe',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'GP',
            ],
            [
                'id'                    => '89',
                'name'                  => 'Guam',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'GU',
            ],
            [
                'id'                    => '90',
                'name'                  => 'Guatemala',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'GT',
            ],
            [
                'id'                    => '91',
                'name'                  => 'Guinea',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'GN',
            ],
            [
                'id'                    => '92',
                'name'                  => 'Guinea-Bissau',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'GW',
            ],
            [
                'id'                    => '93',
                'name'                  => 'Guyana',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'GY',
            ],
            [
                'id'                    => '94',
                'name'                  => 'Haiti',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'HT',
            ],
            [
                'id'                    => '95',
                'name'                  => 'Heard and Mc Donald Islands',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'HM',
            ],
            [
                'id'                    => '96',
                'name'                  => 'Honduras',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'HN',
            ],
            [
                'id'                    => '97',
                'name'                  => 'Hong Kong',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'HK',
            ],
            [
                'id'                    => '98',
                'name'                  => 'Hungary',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'HU',
            ],
            [
                'id'                    => '99',
                'name'                  => 'Iceland',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'IS',
            ],
            [
                'id'                    => '100',
                'name'                  => 'India',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'IN',
            ],
            [
                'id'                    => '101',
                'name'                  => 'Isle of Man',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'IM',
            ],
            [
                'id'                    => '102',
                'name'                  => 'Indonesia',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'ID',
            ],
            [
                'id'                    => '103',
                'name'                  => 'Iran (Islamic Republic of)',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'IR',
            ],
            [
                'id'                    => '104',
                'name'                  => 'Iraq',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'IQ',
            ],
            [
                'id'                    => '105',
                'name'                  => 'Ireland',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'IE',
            ],
            [
                'id'                    => '106',
                'name'                  => 'Israel',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'IL',
            ],
            [
                'id'                    => '107',
                'name'                  => 'Italy',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'IT',
            ],
            [
                'id'                    => '108',
                'name'                  => 'Ivory Coast',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'CI',
            ],
            [
                'id'                    => '109',
                'name'                  => 'Jersey',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'JE',
            ],
            [
                'id'                    => '110',
                'name'                  => 'Jamaica',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'JM',
            ],
            [
                'id'                    => '111',
                'name'                  => 'Japan',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'JP',
            ],
            [
                'id'                    => '112',
                'name'                  => 'Jordan',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'JO',
            ],
            [
                'id'                    => '113',
                'name'                  => 'Kazakhstan',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'KZ',
            ],
            [
                'id'                    => '114',
                'name'                  => 'Kenya',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'KE',
            ],
            [
                'id'                    => '115',
                'name'                  => 'Kiribati',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'KI',
            ],
            [
                'id'                    => '116',
                'name'                  => 'Korea, Democratic People\'s Republic of',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'KP',
            ],
            [
                'id'                    => '117',
                'name'                  => 'Korea, Republic of',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'KR',
            ],
            [
                'id'                    => '118',
                'name'                  => 'Kosovo',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'XK',
            ],
            [
                'id'                    => '119',
                'name'                  => 'Kuwait',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'KW',
            ],
            [
                'id'                    => '120',
                'name'                  => 'Kyrgyzstan',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'KG',
            ],
            [
                'id'                    => '121',
                'name'                  => 'Lao People\'s Democratic Republic',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'LA',
            ],
            [
                'id'                    => '122',
                'name'                  => 'Latvia',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'LV',
            ],
            [
                'id'                    => '123',
                'name'                  => 'Lebanon',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'LB',
            ],
            [
                'id'                    => '124',
                'name'                  => 'Lesotho',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'LS',
            ],
            [
                'id'                    => '125',
                'name'                  => 'Liberia',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'LR',
            ],
            [
                'id'                    => '126',
                'name'                  => 'Libyan Arab Jamahiriya',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'LY',
            ],
            [
                'id'                    => '127',
                'name'                  => 'Liechtenstein',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'LI',
            ],
            [
                'id'                    => '128',
                'name'                  => 'Lithuania',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'LT',
            ],
            [
                'id'                    => '129',
                'name'                  => 'Luxembourg',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'LU',
            ],
            [
                'id'                    => '130',
                'name'                  => 'Macau',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'MO',
            ],
            [
                'id'                    => '131',
                'name'                  => 'North Macedonia',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'MK',
            ],
            [
                'id'                    => '132',
                'name'                  => 'Madagascar',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'MG',
            ],
            [
                'id'                    => '133',
                'name'                  => 'Malawi',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'MW',
            ],
            [
                'id'                    => '134',
                'name'                  => 'Malaysia',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'MY',
            ],
            [
                'id'                    => '135',
                'name'                  => 'Maldives',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'MV',
            ],
            [
                'id'                    => '136',
                'name'                  => 'Mali',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'ML',
            ],
            [
                'id'                    => '137',
                'name'                  => 'Malta',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'MT',
            ],
            [
                'id'                    => '138',
                'name'                  => 'Marshall Islands',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'MH',
            ],
            [
                'id'                    => '139',
                'name'                  => 'Martinique',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'MQ',
            ],
            [
                'id'                    => '140',
                'name'                  => 'Mauritania',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'MR',
            ],
            [
                'id'                    => '141',
                'name'                  => 'Mauritius',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'MU',
            ],
            [
                'id'                    => '142',
                'name'                  => 'Mayotte',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'TY',
            ],
            [
                'id'                    => '143',
                'name'                  => 'Mexico',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'MX',
            ],
            [
                'id'                    => '144',
                'name'                  => 'Micronesia, Federated States of',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'FM',
            ],
            [
                'id'                    => '145',
                'name'                  => 'Moldova, Republic of',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'MD',
            ],
            [
                'id'                    => '146',
                'name'                  => 'Monaco',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'MC',
            ],
            [
                'id'                    => '147',
                'name'                  => 'Mongolia',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'MN',
            ],
            [
                'id'                    => '148',
                'name'                  => 'Montenegro',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'ME',
            ],
            [
                'id'                    => '149',
                'name'                  => 'Montserrat',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'MS',
            ],
            [
                'id'                    => '150',
                'name'                  => 'Morocco',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'MA',
            ],
            [
                'id'                    => '151',
                'name'                  => 'Mozambique',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'MZ',
            ],
            [
                'id'                    => '152',
                'name'                  => 'Myanmar',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'MM',
            ],
            [
                'id'                    => '153',
                'name'                  => 'Namibia',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'NA',
            ],
            [
                'id'                    => '154',
                'name'                  => 'Nauru',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'NR',
            ],
            [
                'id'                    => '155',
                'name'                  => 'Nepal',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'NP',
            ],
            [
                'id'                    => '156',
                'name'                  => 'Netherlands',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'NL',
            ],
            [
                'id'                    => '157',
                'name'                  => 'Netherlands Antilles',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'AN',
            ],
            [
                'id'                    => '158',
                'name'                  => 'New Caledonia',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'NC',
            ],
            [
                'id'                    => '159',
                'name'                  => 'New Zealand',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'NZ',
            ],
            [
                'id'                    => '160',
                'name'                  => 'Nicaragua',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'NI',
            ],
            [
                'id'                    => '161',
                'name'                  => 'Niger',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'NE',
            ],
            [
                'id'                    => '162',
                'name'                  => 'Nigeria',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'NG',
            ],
            [
                'id'                    => '163',
                'name'                  => 'Niue',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'NU',
            ],
            [
                'id'                    => '164',
                'name'                  => 'Norfolk Island',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'NF',
            ],
            [
                'id'                    => '165',
                'name'                  => 'Northern Mariana Islands',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'MP',
            ],
            [
                'id'                    => '166',
                'name'                  => 'Norway',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'NO',
            ],
            [
                'id'                    => '167',
                'name'                  => 'Oman',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'OM',
            ],
            [
                'id'                    => '168',
                'name'                  => 'Pakistan',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'PK',
            ],
            [
                'id'                    => '169',
                'name'                  => 'Palau',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'PW',
            ],
            [
                'id'                    => '170',
                'name'                  => 'Palestine',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'PS',
            ],
            [
                'id'                    => '171',
                'name'                  => 'Panama',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'PA',
            ],
            [
                'id'                    => '172',
                'name'                  => 'Papua New Guinea',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'PG',
            ],
            [
                'id'                    => '173',
                'name'                  => 'Paraguay',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'PY',
            ],
            [
                'id'                    => '174',
                'name'                  => 'Peru',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'PE',
            ],
            [
                'id'                    => '175',
                'name'                  => 'Philippines',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'PH',
            ],
            [
                'id'                    => '176',
                'name'                  => 'Pitcairn',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'PN',
            ],
            [
                'id'                    => '177',
                'name'                  => 'Poland',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'PL',
            ],
            [
                'id'                    => '178',
                'name'                  => 'Portugal',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'PT',
            ],
            [
                'id'                    => '179',
                'name'                  => 'Puerto Rico',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'PR',
            ],
            [
                'id'                    => '180',
                'name'                  => 'Qatar',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'QA',
            ],
            [
                'id'                    => '181',
                'name'                  => 'Reunion',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'RE',
            ],
            [
                'id'                    => '182',
                'name'                  => 'Romania',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'RO',
            ],
            [
                'id'                    => '183',
                'name'                  => 'Russian Federation',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'RU',
            ],
            [
                'id'                    => '184',
                'name'                  => 'Rwanda',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'RW',
            ],
            [
                'id'                    => '185',
                'name'                  => 'Saint Kitts and Nevis',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'KN',
            ],
            [
                'id'                    => '186',
                'name'                  => 'Saint Lucia',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'LC',
            ],
            [
                'id'                    => '187',
                'name'                  => 'Saint Vincent and the Grenadines',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'VC',
            ],
            [
                'id'                    => '188',
                'name'                  => 'Samoa',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'WS',
            ],
            [
                'id'                    => '189',
                'name'                  => 'San Marino',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'SM',
            ],
            [
                'id'                    => '190',
                'name'                  => 'Sao Tome and Principe',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'ST',
            ],
            [
                'id'                    => '191',
                'name'                  => 'Saudi Arabia',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'SA',
            ],
            [
                'id'                    => '192',
                'name'                  => 'Senegal',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'SN',
            ],
            [
                'id'                    => '193',
                'name'                  => 'Serbia',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'RS',
            ],
            [
                'id'                    => '194',
                'name'                  => 'Seychelles',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'SC',
            ],
            [
                'id'                    => '195',
                'name'                  => 'Sierra Leone',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'SL',
            ],
            [
                'id'                    => '196',
                'name'                  => 'Singapore',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'SG',
            ],
            [
                'id'                    => '197',
                'name'                  => 'Slovakia',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'SK',
            ],
            [
                'id'                    => '198',
                'name'                  => 'Slovenia',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'SI',
            ],
            [
                'id'                    => '199',
                'name'                  => 'Solomon Islands',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'SB',
            ],
            [
                'id'                    => '200',
                'name'                  => 'Somalia',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'SO',
            ],
            [
                'id'                    => '201',
                'name'                  => 'South Africa',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'ZA',
            ],
            [
                'id'                    => '202',
                'name'                  => 'South Georgia South Sandwich Islands',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'GS',
            ],
            [
                'id'                    => '203',
                'name'                  => 'South Sudan',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'SS',
            ],
            [
                'id'                    => '204',
                'name'                  => 'Spain',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'ES',
            ],
            [
                'id'                    => '205',
                'name'                  => 'Sri Lanka',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'LK',
            ],
            [
                'id'                    => '206',
                'name'                  => 'St. Helena',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'SH',
            ],
            [
                'id'                    => '207',
                'name'                  => 'St. Pierre and Miquelon',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'PM',
            ],
            [
                'id'                    => '208',
                'name'                  => 'Sudan',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'SD',
            ],
            [
                'id'                    => '209',
                'name'                  => 'Suriname',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'SR',
            ],
            [
                'id'                    => '210',
                'name'                  => 'Svalbard and Jan Mayen Islands',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'SJ',
            ],
            [
                'id'                    => '211',
                'name'                  => 'Swaziland',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'SZ',
            ],
            [
                'id'                    => '212',
                'name'                  => 'Sweden',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'SE',
            ],
            [
                'id'                    => '213',
                'name'                  => 'Switzerland',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'CH',
            ],
            [
                'id'                    => '214',
                'name'                  => 'Syrian Arab Republic',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'SY',
            ],
            [
                'id'                    => '215',
                'name'                  => 'Taiwan',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'TW',
            ],
            [
                'id'                    => '216',
                'name'                  => 'Tajikistan',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'TJ',
            ],
            [
                'id'                    => '217',
                'name'                  => 'Tanzania, United Republic of',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'TZ',
            ],
            [
                'id'                    => '218',
                'name'                  => 'Thailand',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'TH',
            ],
            [
                'id'                    => '219',
                'name'                  => 'Togo',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'TG',
            ],
            [
                'id'                    => '220',
                'name'                  => 'Tokelau',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'TK',
            ],
            [
                'id'                    => '221',
                'name'                  => 'Tonga',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'TO',
            ],
            [
                'id'                    => '222',
                'name'                  => 'Trinidad and Tobago',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'TT',
            ],
            [
                'id'                    => '223',
                'name'                  => 'Tunisia',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'TN',
            ],
            [
                'id'                    => '224',
                'name'                  => 'Turkey',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'TR',
            ],
            [
                'id'                    => '225',
                'name'                  => 'Turkmenistan',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'TM',
            ],
            [
                'id'                    => '226',
                'name'                  => 'Turks and Caicos Islands',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'TC',
            ],
            [
                'id'                    => '227',
                'name'                  => 'Tuvalu',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'TV',
            ],
            [
                'id'                    => '228',
                'name'                  => 'Uganda',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'UG',
            ],
            [
                'id'                    => '229',
                'name'                  => 'Ukraine',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'UA',
            ],
            [
                'id'                    => '230',
                'name'                  => 'United Arab Emirates',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'AE',
            ],
            [
                'id'                    => '231',
                'name'                  => 'United Kingdom',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'GB',
            ],
            [
                'id'                    => '232',
                'name'                  => 'United States',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'US',
            ],
            [
                'id'                    => '233',
                'name'                  => 'United States minor outlying islands',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'UM',
            ],
            [
                'id'                    => '234',
                'name'                  => 'Uruguay',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'UY',
            ],
            [
                'id'                    => '235',
                'name'                  => 'Uzbekistan',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'UZ',
            ],
            [
                'id'                    => '236',
                'name'                  => 'Vanuatu',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'VU',
            ],
            [
                'id'                    => '237',
                'name'                  => 'Vatican City State',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'VA',
            ],
            [
                'id'                    => '238',
                'name'                  => 'Venezuela',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'VE',
            ],
            [
                'id'                    => '239',
                'name'                  => 'Việt Nam',
                'name_en'               => 'Vietnam',
                'description'           => null,
                'code_no'               => 'VN',
            ],
            [
                'id'                    => '240',
                'name'                  => 'Virgin Islands (British)',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'VG',
            ],
            [
                'id'                    => '241',
                'name'                  => 'Virgin Islands (U.S.)',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'VI',
            ],
            [
                'id'                    => '242',
                'name'                  => 'Wallis and Futuna Islands',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'WF',
            ],
            [
                'id'                    => '243',
                'name'                  => 'Western Sahara',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'EH',
            ],
            [
                'id'                    => '244',
                'name'                  => 'Yemen',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'YE',
            ],
            [
                'id'                    => '245',
                'name'                  => 'Zambia',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'ZM',
            ],
            [
                'id'                    => '246',
                'name'                  => 'Zimbabwe',
                'name_en'               => '-',
                'description'           => null,
                'code_no'               => 'ZW',
            ],




        ];
        AdminAddressNation::insert($data);
    }
} 